baseURL = "http://miyamam.github.io/"
languageCode = "ja"
title = "My Technical Note"
theme = "kraiklyn"
themesDir = "./themes"
canonifyurls = true

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
externalTitle = "参考リンク"
subtitle = "備忘録がてら残したものです"
author = "Miho Yamamoto"

[[menu.shortcuts]]
name = "miyamam on Github"
url = "https://github.com/miyamam"
weight = 10

[[menu.shortcuts]]
name = "Kraiklyn on Github"
url = "https://github.com/jsnjack/kraiklyn"
weight = 20

[[menu.shortcuts]]
name = "Hugo docs"
url = "https://gohugo.io/documentation/"
weight = 30

